// 4-react/22-ts/2-props/app1/src/components/Counter/index.tsx
import { useState } from "react"

export const Counter = () => {
  const [count, setCount] = useState(0)

  const increment = () => setCount((prev) => prev + 1)
  const decrement = () => setCount((prev) => prev - 1)
  const reset = () => setCount(0)

  return (
    <>
      <p>Counter: {count}</p>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
      <button onClick={reset}>RESET</button>
    </>
  )
}

export default Counter

// 5-vue/1-vue3/7-if/app1/src/components/Counter.vue
<template>
  <div>
  <h1>Counter</h1>
  <p>Count: {{ count }}</p>
  <button @click="plus">+</button>
  <button @click="minus">+</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const plus = () => {
  count.value = count.value + 1
}
const minus = () => {
  count.value = count.value - 1
}
</script>

<style scoped>
</style>
