// 4-react/17-tailwindcss-2/app1/src/components/Movies.js
import React from "react";
import Box from "@mui/material/Box";
import Rating from "@mui/material/Rating";
import CircularProgress from "@mui/material/CircularProgress";
import Tooltip from "@mui/material/Tooltip";
import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { useState, useEffect } from "react";

export default function Movies() {
  const [movies, setMovies] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  // mounted
  useEffect(() => {
    // Loading中のフラグ
    setIsLoading(true);
    //fetch("https://yts.mx/api/v2/list_movies.json?sort_by=rating")
    fetch("https://yts.mx/api/v2/list_movies.json")
      .then((res) => res.json())
      .then((json) => {
        setIsLoading(false);
        setMovies(json.data.movies);
      });
  }, []);

  console.log("movies: ", movies);

  const loading = (
    <Box sx={{ display: "flex" }}>
      <CircularProgress />
    </Box>
  );

  const render = movies.map((movie) => {
    return (
      <div key={movie.id}>
        <a
          className="block text-gray-500 text-[24px] font-bold no-underline p-[5px] m-[10px] border-[1px] border-white rounded-[5px] hover:bg-red-300 hover:text-white"
          href={movie.url}
        >
          {movie.title}({movie.year})
        </a>

        <img
          className="block w-[300px]"
          src={movie.large_cover_image}
          alt={movie.title}
        ></img>

        <div className="my-[10px]">
          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel1-content"
              id="panel1-header"
            >
              詳細を見る
            </AccordionSummary>
            <AccordionDetails>
              <div>
                評価：
                <Tooltip title={movie.rating + "/10点"} placement="right">
                  <Box
                    display="inline"
                    sx={{
                      "& > legend": { mt: 2 },
                    }}
                  >
                    <Rating
                      size="small"
                      name="simple-controlled"
                      readOnly
                      value={movie.rating / 2}
                    />
                  </Box>
                </Tooltip>
              </div>
              <div>ジャンル：{movie.genres.join(", ")}</div>
              <div>ランタイム：{movie.runtime}分</div>
              <div>ストーリー{movie.synopsis || "情報なし"}</div>
            </AccordionDetails>
          </Accordion>
        </div>
      </div>
    );
  });

  return (
    <div>
      <h1 className="text-[36px] font-bold">Movies</h1>
      <div>{render}</div>
    </div>
  );
}

// 5-vue/1-vue3/8-v-model/app1/src/components/Movies.vue
<template>
  <div>
  <h1>Movies</h1>
    <div v-for="movie in movies" :key="movie.title" class="movieItem">
      <a class="movieTitle" :href="movie.url" target="blank">{{ movie.title }} ({{ movie.year }})</a>
      <img class="movieImage" :src="movie.large_cover_image" :alt="movie.title" />
      <div class="movieRating">評価:{{ movie.rating }} / 10</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

// Types
interface Movie {
  title: string
  year: number
  url: string
  large_cover_image: string
  rating: number
}

const movies = ref<Movie[]>([]) 

onMounted(() => {
  fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
  .then(response => response.json())
  .then(json => {
  movies.value = json.data.movies
  })
})
</script>

<style scoped>
.movieItem {
  margin-bottom: 20px;
}

.movieTitle {
  font-size: 20px;
  color: gray;
  text-decoration: none;
}

.movieTitle:hover {
  color: pink;
}

.movieImage {
  display: block;
  width: 50px;
}

.movieRating {
  color: gray;
}
</style>
