// 5-vue/1-vue3/8-v-model/app1/src/components/Movies.vue
<template>
  <div>
  <h1>Movies</h1>
    <div v-for="movie in movies" :key="movie.title" class="movieItem">
      <a class="movieTitle" :href="movie.url" target="blank">{{ movie.title }} ({{ movie.year }})</a>
      <img class="movieImage" :src="movie.large_cover_image" :alt="movie.title" />
      <div class="movieRating">評価:{{ movie.rating }} / 10</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

// Types
interface Movie {
  title: string
  year: number
  url: string
  large_cover_image: string
  rating: number
}

const movies = ref<Movie[]>([]) 

onMounted(() => {
  fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
  .then(response => response.json())
  .then(json => {
  movies.value = json.data.movies
  })
})
</script>

<style scoped>
.movieItem {
  margin-bottom: 20px;
}

.movieTitle {
  font-size: 20px;
  color: gray;
  text-decoration: none;
}

.movieTitle:hover {
  color: pink;
}

.movieImage {
  display: block;
  width: 50px;
}

.movieRating {
  color: gray;
}
</style>

// 4-react/21-router-tdd/app1/src/components/Movies.js
import React, { useState, useEffect } from "react";
import "./Movie.css";

export default function Movies() {
  const [movies, setMovies] = useState([]);

  const movieRatingClass = (rating) => {
    return rating >= 9 ? "good" : rating >= 7 ? "soso" : "bad";
  };

  // mounted
  useEffect(() => {
    fetch("https://yts.mx/api/v2/list_movies.json")
      .then((res) => res.json())
      .then((json) => {
        setMovies(json.data.movies);
      });
  }, []);

  const render = movies.map((movie) => {
    return (
      <div key={movie.id}>
        <a className="movieTitle" href={movie.url}>
          {movie.title} ({movie.year})
        </a>
        <div>
          評価:
          <span className={movieRatingClass(movie.rating)}>{movie.rating}</span>
          /10点
        </div>
        <div>ジャンル: {movie.genres.join(", ")}</div>
        <div>ランタイム: {movie.runtime}分</div>
        <div>ストーリー: {movie.synopsis || "情報なし"}</div>
        <img
          className="movieImg"
          src={movie.large_cover_image}
          alt={movie.title}
        />
      </div>
    );
  });

  return (
    <div>
      <h1>Movies</h1>
      <div>{render}</div>
    </div>
  );
}
