// 5-vue/1-vue3/7-v-if/app1/src/components/Movies.vue
<template>
  <div>
  <h1>Movies</h1>
  <ul>
    <li v-for="movie in movies" :key="movie.title">
      {{  movie.title }} ({{ movie.year }})
    </li>
  </ul>
  </div>
</template>

<script setup lang="ts">
import { reactive } from 'vue'

// ref -> number, string, boolean, null, object
// reactive -> array

const movies = reactive([
  { title: 'Movie 1', year: 2021 },
  { title: 'Movie 2', year: 2022 },
  { title: 'Movie 3', year: 2023 },
  { title: 'Movie 4', year: 2024 },
  { title: 'Movie 5', year: 2025 },
]) 

movies.push({ title: 'Movie 6', year: 2026 })
</script>

<style scoped>
</style>

// 4-react/22-ts/3-movieapp/app1/src/components/Movies/index.tsx
import { MoviesProps } from '../../common/types'

const Movies: React.FC<MoviesProps> = ({ movies }) => {
  return (
    <div>
      {movies.map((movie, index) => (
        <div key={index}>
          <img src={movie.large_cover_image} alt={movie.title} />
          <div>{movie.title}({movie.year})</div>
          <div>Rating: {movie.rating}/10</div>
        </div>
      ))}
    </div>
  )
}

export default Movies;
